<?php

ob_start();
// Start session
session_start();

// Get count of ads in the database



// Send cookie if cookie does not exist
if((isset($_COOKIE['_URLCASH_COOKIE_TP9235'])) and (($_SESSION['_URL$CASH_8398fh48qo8732^%RTD**(#Y*#YT*&FH#YR)_TPCATRICK&%(*#RFB101038']) == true))
{
    // Click already recorded, do nothing
}
else
{
    // Set cookie 
    setcookie('_URLCASH_COOKIE_TP9235',true,time()+86400);
    $_SESSION['_URL$CASH_8398fh48qo8732^%RTD**(#Y*#YT*&FH#YR)_TPCATRICK&%(*#RFB101038'] = true;
    
    // Get count of ads in the database
    
}
ob_end_flush();
?>