<?php

/**
=-----------------------------------------------------------------------

  PHP dbConfig   -> dbConfig.inc EXTENDS mysqlConnect

----------------------------------------------------------------------=

This file contains the login information for Mysql Database, and is an extension of the libphp.connectMysql.0-1.inc library
------------------------------------------------------------------------
  
License
--------------------------------------------------------------------------
This is licensed under the GPL version 3 and greater. For more information see /GPL or http://www.gnu.org/licenses/gpl.txt
This code library is provided as is, and has no guarantee. 
--------------------------------------------------------------------------

$mysql_host = "localhost";
$mysql_database = "DATABASE NAME";
$mysql_user = "DATABASE USERNAME";
$mysql_password = "PASSWORD";

*/

define('DB_SERVER', 'localhost');
define('DB_USERNAME', 'DATABASE USERNAME');
define('DB_PW', 'PASSWORD');
define('DB', 'DATABASE NAME');

?> 
